{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7e7bba31-0ee2-4dad-901f-208415847d9c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# train.py\n",
    "import os\n",
    "import numpy as np\n",
    "from tensorflow.keras.utils import to_categorical\n",
    "from tensorflow.keras.models import Model, Sequential\n",
    "from tensorflow.keras.layers import (Dense, Conv2D, MaxPooling2D, Flatten,\n",
    "                                     LSTM, TimeDistributed, Input, Dropout)\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint\n",
    "from tensorflow.keras.applications import ResNet50\n",
    "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
    "\n",
    "from utils.data_loader import load_mnist, load_emnist, load_devanagari\n",
    "\n",
    "# ----------------------------\n",
    "# Utility functions\n",
    "# ----------------------------\n",
    "def preprocess_data(x, y, num_classes):\n",
    "    y = to_categorical(y, num_classes)\n",
    "    return x, y\n",
    "\n",
    "def create_cnn(input_shape, num_classes):\n",
    "    model = Sequential([\n",
    "        Conv2D(32, (3,3), activation='relu', input_shape=input_shape),\n",
    "        MaxPooling2D(),\n",
    "        Conv2D(64, (3,3), activation='relu'),\n",
    "        MaxPooling2D(),\n",
    "        Flatten(),\n",
    "        Dense(128, activation='relu'),\n",
    "        Dense(num_classes, activation='softmax')\n",
    "    ])\n",
    "    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])\n",
    "    return model\n",
    "\n",
    "def create_lstm(input_shape, num_classes):\n",
    "    model = Sequential([\n",
    "        TimeDistributed(Dense(64, activation='relu'), input_shape=input_shape),\n",
    "        LSTM(128),\n",
    "        Dense(num_classes, activation='softmax')\n",
    "    ])\n",
    "    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])\n",
    "    return model\n",
    "\n",
    "def create_vit(input_shape, num_classes):\n",
    "    inputs = Input(shape=input_shape)\n",
    "    base_model = ResNet50(include_top=False, weights=None, input_tensor=inputs, pooling='avg')\n",
    "    x = Flatten()(base_model.output)\n",
    "    outputs = Dense(num_classes, activation='softmax')(x)\n",
    "    model = Model(inputs, outputs)\n",
    "    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])\n",
    "    return model\n",
    "\n",
    "def create_hybrid(input_shape, num_classes):\n",
    "    inputs = Input(shape=input_shape)\n",
    "    # CNN branch\n",
    "    x = Conv2D(32, (3,3), activation='relu')(inputs)\n",
    "    x = MaxPooling2D()(x)\n",
    "    x = Flatten()(x)\n",
    "    # Dense branch\n",
    "    y = Dense(128, activation='relu')(x)\n",
    "    outputs = Dense(num_classes, activation='softmax')(y)\n",
    "    model = Model(inputs, outputs)\n",
    "    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])\n",
    "    return model\n",
    "\n",
    "def train_models(x_train, y_train, x_test, y_test, dataset_name, input_shape):\n",
    "    num_classes = y_train.shape[1]\n",
    "    models = {\n",
    "        'cnn': create_cnn(input_shape, num_classes),\n",
    "        'lstm': create_lstm(input_shape, num_classes),\n",
    "        'vit': create_vit(input_shape, num_classes),\n",
    "        'hybrid': create_hybrid(input_shape, num_classes)\n",
    "    }\n",
    "\n",
    "    os.makedirs('models', exist_ok=True)\n",
    "\n",
    "    for name, model in models.items():\n",
    "        print(f\"\\nTraining {name.upper()} on {dataset_name} dataset...\")\n",
    "        checkpoint = ModelCheckpoint(f'models/{dataset_name}_{name}.h5', save_best_only=True, monitor='val_accuracy', mode='max')\n",
    "        model.fit(\n",
    "            x_train, y_train,\n",
    "            validation_data=(x_test, y_test),\n",
    "            epochs=5,\n",
    "            batch_size=64,\n",
    "            callbacks=[checkpoint],\n",
    "            verbose=2\n",
    "        )\n",
    "        print(f\"{name.upper()} training completed!\")\n",
    "\n",
    "# ----------------------------\n",
    "# Main\n",
    "# ----------------------------\n",
    "if __name__ == '__main__':\n",
    "    # MNIST\n",
    "    x_train, y_train, x_test, y_test = load_mnist()\n",
    "    x_train, y_train = preprocess_data(x_train, y_train, 10)\n",
    "    x_test, y_test = preprocess_data(x_test, y_test, 10)\n",
    "    train_models(x_train, y_train, x_test, y_test, 'mnist', x_train.shape[1:])\n",
    "\n",
    "    # EMNIST\n",
    "    x_train, y_train, x_test, y_test = load_emnist()\n",
    "    x_train, y_train = preprocess_data(x_train, y_train, 26)\n",
    "    x_test, y_test = preprocess_data(x_test, y_test, 26)\n",
    "    train_models(x_train, y_train, x_test, y_test, 'emnist', x_train.shape[1:])\n",
    "\n",
    "    # Devanagari\n",
    "    x_train, y_train, x_test, y_test, class_map = load_devanagari()\n",
    "    num_classes = len(class_map)\n",
    "    y_train = to_categorical(y_train, num_classes)\n",
    "    y_test = to_categorical(y_test, num_classes)\n",
    "    train_models(x_train, y_train, x_test, y_test, 'devanagari', x_train.shape[1:])\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
